version: '3.1'
#networks:
  #kafka_net: null
services:
  kafka:
    container_name: kafka
    image: wurstmeister/kafka:2.11-2.0.0
    links:
      - zookeeper
    ports:
     - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      #KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      #KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      #KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      #KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
    #networks:
      #- kafka_net
    depends_on:
      - zookeeper

  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.4
    restart: always
    ports:
      - 32181:2181
    environment:
      ZOO_TICK_TIME: 4000
    #networks:
      #- kafka_net

  orders_db:
    container_name: ordersDB
    image: postgres:10.5
    restart: always
    ports:
      - 35433:5432
    environment:
      POSTGRES_PASSWORD: exectemp
      POSTGRES_DB: orders
      POSTGRES_USER: postgres
