spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  datasource:
    url: jdbc:postgresql://localhost:35433/orders
    username: postgres
    password: exectemp
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: order_con_pool
      maximum-pool-size: 10
  flyway:
    enabled: true
    check-location: true
    locations: classpath:/db_scripts

logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace
      springframework: trace
      apache:
        kafka: trace
server:
  port: 9999

kafka:
  ordertopic: kafka_orders
  broker: localhost:29092



